### ISSUE TITLE
please update floki to 0.34.0 to make it compatible with phoenix 1.7

### ISSUE THREAD

**Issue by nickkaltner** [wojtekmach/easyhtml#1]
please update floki to 0.34.0 to make it compatible with phoenix 1.7

**Comment by wojtekmach** [comment]
What version of Floki does Phoenix 1.7 apps depend on? I could only find https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.3/mix.exs#L46 and it's not compatible with 0.34.0 either. Just to be clear, I'm happy to update the requirement, but want to understand the scenario you run into.

**Comment by wojtekmach** [comment]
ok, found it, https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.0/installer/templates/phx_single/mix.exs#L47.

**Comment by wojtekmach** [comment]
v0.1.1 is out!
